apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: cpoulin/taskandgo
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s-deployment.yaml
portForward:
  - resourceType: Service
    resourceName: taskandgo-service
    port: 50051
    localPort: 50051
